Updated nginx init.d script

diff --git a/nginx/nginx b/nginx/nginx
--- a/nginx/nginx
+++ b/nginx/nginx
@@ -5,11 +5,12 @@
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: nginx init.d script for Ubuntu 8.10 and lesser versions.
-# Description:       nginx init.d script for Ubuntu 8.10 and lesser versions.
+# Short-Description: nginx init.d dash script for Ubuntu <=9.10.
+# Description:       nginx init.d dash script for Ubuntu <=9.10.
 ### END INIT INFO
 #------------------------------------------------------------------------------
-# nginx - this script, which starts and stops the nginx daemon for ubuntu.
+# nginx - this Debian Almquist shell (dash) script, starts and stops the nginx 
+#         daemon for ubuntu 9.10 and lesser version numbered releases.
 #
 # description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
 #               proxy and IMAP/POP3 proxy server.  This \
@@ -22,16 +23,20 @@
 # Provides:    nginx
 #
 # Author:  Jason Giedymin
-#          <jason.giedymin AT acronymlabs.com>.
+#          <jason.giedymin AT gmail.com>.
 #
-# Version: 1.0 01-Apr-2009 jason.giedymin AT gmail.com
-# Notes: nginx init.d script for Ubuntu 8.10 and lesser versions.
+# Version: 2.0 02-NOV-2009 jason.giedymin AT gmail.com
+# Notes: nginx init.d dash script for Ubuntu <=9.10.
+# 
+# This script's project home is:
+# 	http://code.google.com/p/nginx-init-ubuntu/
 #
 #------------------------------------------------------------------------------
 #                               MIT X11 License
 #------------------------------------------------------------------------------
 #
-# Copyright (c) 2009 Jason Giedymin, http://AcronymLabs.com
+# Copyright (c) 2009 Jason Giedymin, http://Amuxbit.com formerly
+#				     http://AcronymLabs.com
 #
 # Permission is hereby granted, free of charge, to any person obtaining
 # a copy of this software and associated documentation files (the
@@ -62,23 +67,24 @@
 #                               Consts
 #------------------------------------------------------------------------------
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/opt/nginx/sbin/nginx
+DAEMON=/usr/local/sbin/nginx
 
 PS="nginx"
-PIDNAME="nginx"				#Lets you do $PS-Master or $PS-Slave
+PIDNAME="nginx"				#lets you do $PS-slave
 PIDFILE=$PIDNAME.pid                    #pid file
-PIDSPATH=/opt/nginx/logs
+PIDSPATH=/var/run
+
 DESCRIPTION="Nginx Server..."
 
-RUNAS=root				#user to run as
+RUNAS=root                              #user to run as
 
-SCRIPT_OK=0				#ala error codes
-SCRIPT_ERROR=1				#ala error codes
-TRUE=1					#boolean
-FALSE=0					#boolean
+SCRIPT_OK=0                             #ala error codes
+SCRIPT_ERROR=1                          #ala error codes
+TRUE=1                                  #boolean
+FALSE=0                                 #boolean
 
 lockfile=/var/lock/subsys/nginx
-NGINX_CONF_FILE="/opt/nginx/conf/nginx.conf"
+NGINX_CONF_FILE="/usr/local/nginx/conf/nginx.conf"
 
 #------------------------------------------------------------------------------
 #                               Simple Tests
@@ -102,7 +108,7 @@ fi
 setFilePerms(){
 
         if [ -f $PIDSPATH/$PIDFILE ]; then
-                chmod -f 400 $PIDSPATH/$PIDFILE
+                chmod 400 $PIDSPATH/$PIDFILE
         fi
 }
 
@@ -114,15 +120,54 @@ getPSCount() {
 	return `pgrep -f $PS | wc -l`
 }
 
-isRunning(){
-	pidof_daemon
-	PID=$?
+isRunning() {
+        if [ $1 ]; then
+                pidof_daemon $1
+                PID=$?
 
-	if [ $PID -gt 0 ]; then
-		return 1
+                if [ $PID -gt 0 ]; then
+                        return 1
+                else
+                        return 0
+                fi
         else
-                return 0
+                pidof_daemon
+                PID=$?
+
+                if [ $PID -gt 0 ]; then
+                        return 1
+                else
+                        return 0
+                fi
         fi
+}
+
+#courtesy of php-fpm
+wait_for_pid () {
+        try=0
+
+        while test $try -lt 35 ; do
+
+                case "$1" in
+                        'created')
+                        if [ -f "$2" ] ; then
+                                try=''
+                                break
+                        fi
+                        ;;
+
+                        'removed')
+                        if [ ! -f "$2" ] ; then
+                                try=''
+                                break
+                        fi
+                        ;;
+                esac
+
+                #echo -n .
+                try=`expr $try + 1`
+                sleep 1
+        done
 }
 
 status(){
@@ -139,8 +184,15 @@ status(){
 }
 
 removePIDFile(){
-	if [ -f $PIDSPATH/PIDFILE ]; then
-        	rm -f $PIDSPATH/$PIDFILE
+	if [ $1 ]; then
+                if [ -f $1 ]; then
+        	        rm -f $1
+	        fi
+        else
+		#Do default removal
+		if [ -f $PIDSPATH/$PIDFILE ]; then
+        	        rm -f $PIDSPATH/$PIDFILE
+	        fi
         fi
 }
 
@@ -153,9 +205,10 @@ start() {
         if [ "${isAlive}" -eq $TRUE ]; then
                 log_end_msg $SCRIPT_ERROR
         else
-                start-stop-daemon --start --quiet --chuid $RUNAS --pidfile $PIDSPATH/$PIDFILE --exec $DAEMON
+                start-stop-daemon --start --quiet --chuid $RUNAS --pidfile $PIDSPATH/$PIDFILE --exec $DAEMON \
+                -- -c $NGINX_CONF_FILE
                 setFilePerms
-		log_end_msg $SCRIPT_OK
+                log_end_msg $SCRIPT_OK
         fi
 }
 
@@ -167,9 +220,15 @@ stop() {
         if [ "${isAlive}" -eq $TRUE ]; then
                 start-stop-daemon --stop --quiet --pidfile $PIDSPATH/$PIDFILE
 
-		removePIDFile
+		wait_for_pid 'removed' $PIDSPATH/$PIDFILE
 
-                log_end_msg $SCRIPT_OK
+                if [ -n "$try" ] ; then
+                        log_end_msg $SCRIPT_ERROR
+                else
+                        removePIDFile
+	                log_end_msg $SCRIPT_OK
+                fi
+
         else
                 log_end_msg $SCRIPT_ERROR
         fi
@@ -190,6 +249,42 @@ reload() {
         fi
 }
 
+quietupgrade() {
+	log_daemon_msg "Peforming Quiet Upgrade $DESCRIPTION"
+
+        isRunning
+        isAlive=$?
+        if [ "${isAlive}" -eq $TRUE ]; then
+		kill -USR2 `cat $PIDSPATH/$PIDFILE`
+		kill -WINCH `cat $PIDSPATH/$PIDFILE.oldbin`
+		
+		isRunning
+		isAlive=$?
+		if [ "${isAlive}" -eq $TRUE ]; then
+			kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
+			wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
+                        removePIDFile $PIDSPATH/$PIDFILE.oldbin
+
+			log_end_msg $SCRIPT_OK
+		else
+			log_end_msg $SCRIPT_ERROR
+			
+			log_daemon_msg "ERROR! Reverting back to original $DESCRIPTION"
+
+			kill -HUP `cat $PIDSPATH/$PIDFILE`
+			kill -TERM `cat $PIDSPATH/$PIDFILE.oldbin`
+			kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
+
+			wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
+                        removePIDFile $PIDSPATH/$PIDFILE.oldbin
+
+			log_end_msg $SCRIPT_ok
+		fi
+        else
+                log_end_msg $SCRIPT_ERROR
+        fi
+}
+
 terminate() {
         log_daemon_msg "Force terminating (via KILL) $DESCRIPTION"
         
@@ -200,12 +295,18 @@ terminate() {
 	for i in $PIDS; do
 		if [ "$i" = "$PIDS2" ]; then
 	        	kill $i
+                        wait_for_pid 'removed' $PIDSPATH/$PIDFILE
 			removePIDFile
 		fi
 	done
 
 	log_end_msg $SCRIPT_OK
+}
 
+destroy() {
+	log_daemon_msg "Force terminating and may include self (via KILLALL) $DESCRIPTION"
+	killall $PS -q >> /dev/null 2>&1
+	log_end_msg $SCRIPT_OK
 }
 
 pidof_daemon() {
@@ -230,6 +331,7 @@ case "$1" in
         ;;
   restart|force-reload)
 	stop
+	sleep 1
 	start
         ;;
   reload)
@@ -241,12 +343,19 @@ case "$1" in
   configtest)
         $1
         ;;
+  quietupgrade)
+	$1
+	;;
   terminate)
 	$1
 	;;
+  destroy)
+	$1
+	;;
   *)
-	FULLPATH=/etc/init.d/$PIDNAME
-	echo "Usage: $FULLPATH {start|stop|restart|force-reload|status|configtest|terminate}"
+	FULLPATH=/etc/init.d/$PS
+	echo "Usage: $FULLPATH {start|stop|restart|force-reload|status|configtest|quietupgrade|terminate|destroy}"
+	echo "       The 'destroy' command should only be used as a last resort." 
 	exit 1
 	;;
 esac
